ParameterFilterOptionDecorator:
    type: input-object
    decorator: true
    config:
        description: "Parameter filter option"
        fields:
            parameter:
                type: "Parameter!"
                description: "Parameter"
            values:
                type: "[ParameterValueFilterOption!]!"
                description: "Filter options of parameter values"
