ParameterFilterDecorator:
    type: input-object
    decorator: true
    config:
        description: "Represents a parameter filter"
        fields:
            parameter:
                type: "Uuid"
            values:
                type: "[Uuid]"
